ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - examples/*

strictPeerDependencies: false

allowBuilds:
  esbuild: false
  vue-demi: false
