packages:
  - examples/*

ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false

onlyBuiltDependencies:
  - core-js
  - esbuild
  - unrs-resolver
  - vue-demi
