// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    AImage: typeof import('ant-design-vue/es')['Image']
    AImagePreviewGroup: typeof import('ant-design-vue/es')['ImagePreviewGroup']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ATable: typeof import('ant-design-vue/es')['Table']
  }
}

export { }
