// generated by unplugin-vue-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NInput: typeof import('naive-ui')['NInput']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NSpace: typeof import('naive-ui')['NSpace']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  }
}

export { }
