/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/global/avatar.vue')['default']
    Book: typeof import('./src/components/book/index.vue')['default']
    CollapseCollapseFolderAndCollapseFolderAndComponentPrefixes: typeof import('./src/components/collapse/collapseFolderAnd/CollapseFolderAndComponentPrefixes.vue')['default']
    CollapseCollapseFolderCollapseFolderAndComponentFromRoot: typeof import('./src/components/collapse/collapseFolder/CollapseFolderAndComponentFromRoot.vue')['default']
    CollapseCollapseFolderFolderAndComponentPartially: typeof import('./src/components/collapse/collapseFolder/FolderAndComponentPartially.vue')['default']
    ComponentA: typeof import('./src/components/ComponentA.vue')['default']
    ComponentAsync: typeof import('./src/components/ComponentAsync.vue')['default']
    ComponentB: typeof import('./src/components/ComponentB.vue')['default']
    ComponentC: typeof import('./src/components/component-c.vue')['default']
    ComponentD: typeof import('./src/components/ComponentD.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElMessage: typeof import('element-plus/es')['ElMessage']
    ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
    IFaSolidDiceFive: typeof import('~icons/fa-solid/dice-five')['default']
    IHeroiconsOutlineMenuAlt2: typeof import('~icons/heroicons-outline/menu-alt2')['default']
    'IMdi:diceD12': typeof import('~icons/mdi/dice-d12')['default']
    IMdiLightAlarm: typeof import('~icons/mdi-light/alarm')['default']
    IRiApps2Line: typeof import('~icons/ri/apps2-line')['default']
    MarkdownA: typeof import('./src/components/MarkdownA.md')['default']
    MarkdownB: typeof import('./src/components/MarkdownB.md')['default']
    MyCustom: typeof import('./src/CustomResolved.vue')['default']
    Recursive: typeof import('./src/components/Recursive.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./src/components/ui/button.vue')['default']
    UiNestedCheckbox: typeof import('./src/components/ui/nested/checkbox.vue')['default']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRate: typeof import('vant/es')['Rate']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
