// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonSvg: typeof import('./src/components/CarbonSvg.svg')
    ComponentA: typeof import('./src/components/ComponentA.vue')
    ComponentB: typeof import('./src/components/ComponentB.vue')
    ComponentD: typeof import('./src/components/ComponentD.vue')
    MarkdownA: typeof import('./src/components/MarkdownA.md')
    MarkdownB: typeof import('./src/components/MarkdownB.md')
    Recursive: typeof import('./src/components/Recursive.vue')
    ComponentC: typeof import('./src/components/component-c.vue')
    Book: typeof import('./src/components/book/index.vue')
    Avatar: typeof import('./src/components/global/avatar.vue')
    UiButton: typeof import('./src/components/ui/button.vue')
    UiNestedCheckbox: typeof import('./src/components/ui/nested/checkbox.vue')
  }
}

export { }
