// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonSvg: typeof import('./src/components/CarbonSvg.svg')['default']
    ComponentA: typeof import('./src/components/ComponentA.vue')['default']
    ComponentB: typeof import('./src/components/ComponentB.vue')['default']
    ComponentD: typeof import('./src/components/ComponentD.vue')['default']
    MarkdownA: typeof import('./src/components/MarkdownA.md')['default']
    MarkdownB: typeof import('./src/components/MarkdownB.md')['default']
    Recursive: typeof import('./src/components/Recursive.vue')['default']
    ComponentC: typeof import('./src/components/component-c.vue')['default']
    Book: typeof import('./src/components/book/index.vue')['default']
    Avatar: typeof import('./src/components/global/avatar.vue')['default']
    UiButton: typeof import('./src/components/ui/button.vue')['default']
    UiNestedCheckbox: typeof import('./src/components/ui/nested/checkbox.vue')['default']
    MyCustom: typeof import('./src/CustomResolved.vue')['default']
    VanRate: typeof import('vant/es')['Rate']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    IFaSolidDiceFive: typeof import('virtual:vite-icons/fa-solid/dice-five')['default']
    IHeroiconsOutlineMenuAlt2: typeof import('virtual:vite-icons/heroicons-outline/menu-alt2')['default']
    IRiApps2Line: typeof import('virtual:vite-icons/ri/apps2-line')['default']
    'IMdi:diceD12': typeof import('virtual:vite-icons/mdi/dice-d12')['default']
    IMdiLightAlarm: typeof import('virtual:vite-icons/mdi-light/alarm')['default']
  }
}

export { }
